spring.application.name=gilded

spring.sql.init.mode=always

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.profiles.active=local

spring.jpa.properties.hibernate.globally_quoted_identifiers=true

server.port=2006